ANALYSIS_DIR = "dat/analysis"
D_DATA_FILENAME = ANALYSIS_DIR + "/raw_data_dense.csv"
S_DATA_FILENAME = ANALYSIS_DIR + "/raw_data_sparse.csv"
D_RUNTIME_SUMMARY = ANALYSIS_DIR + "/summary/runtime_dense.csv"
S_RUNTIME_SUMMARY = ANALYSIS_DIR + "/summary/runtime_sparse.csv"
D_EXPLORED_SUMMARY = ANALYSIS_DIR + "/summary/explored_dense.csv"
S_EXPLORED_SUMMARY = ANALYSIS_DIR + "/summary/explored_sparse.csv"
D_SOLUTION_SUMMARY = ANALYSIS_DIR + "/summary/solution_dense.csv"
S_SOLUTION_SUMMARY = ANALYSIS_DIR + "/summary/solution_sparse.csv"

PLOT_DIR = ANALYSIS_DIR + "/plot"
RUNTIME_PLOT = PLOT_DIR + "/runtime.png"
EXPLORED_PLOT = PLOT_DIR + "/explored.png"
SOLUTION_PLOT = PLOT_DIR + "/solution.png"
